"""All 13 Saudi region profiles with cities, bounds, populations, and grid settings."""

__all__ = ["REGIONS"]

REGIONS: dict = {
    "Riyadh_Region": {
        "name_en": "Riyadh Region",
        "name_ar": "منطقة الرياض",
        "aliases": ["riyadh", "الرياض", "riyad"],
        "cities": {
            "Riyadh": {
                "name_ar": "الرياض",
                "aliases": ["riyadh city", "riad"],
                "population": 7_500_000,
                "bounds": {"north": 24.85, "south": 24.55, "west": 46.55, "east": 46.85},
                "base_grid_step_km": 1.5,
                "radius": 1500,
            },
            "Kharj": {
                "name_ar": "الخرج",
                "aliases": ["al kharj", "alkharj"],
                "population": 425_000,
                "bounds": {"north": 24.18, "south": 24.12, "west": 47.28, "east": 47.35},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
            "Dawadmi": {
                "name_ar": "الدوادمي",
                "aliases": ["al dawadmi", "dawadmi"],
                "population": 75_000,
                "bounds": {"north": 24.52, "south": 24.48, "west": 44.37, "east": 44.42},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Majmaah": {
                "name_ar": "المجمعة",
                "aliases": ["al majmaah", "majma"],
                "population": 60_000,
                "bounds": {"north": 25.92, "south": 25.88, "west": 45.33, "east": 45.38},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Afif": {
                "name_ar": "عفيف",
                "aliases": [],
                "population": 45_000,
                "bounds": {"north": 23.93, "south": 23.89, "west": 42.90, "east": 42.95},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Wadi_Aldawaser": {
                "name_ar": "وادي الدواسر",
                "aliases": ["wadi dawasir"],
                "population": 50_000,
                "bounds": {"north": 20.48, "south": 20.43, "west": 44.82, "east": 44.88},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Shaqra": {
                "name_ar": "شقراء",
                "aliases": [],
                "population": 35_000,
                "bounds": {"north": 25.26, "south": 25.22, "west": 45.24, "east": 45.29},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Hotat_Bani_Tamim": {
                "name_ar": "حوطة بني تميم",
                "aliases": ["hotat tamim"],
                "population": 30_000,
                "bounds": {"north": 23.55, "south": 23.51, "west": 46.84, "east": 46.89},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Makkah_Region": {
        "name_en": "Makkah Region",
        "name_ar": "منطقة مكة المكرمة",
        "aliases": ["makkah", "mecca", "مكة", "مكة المكرمة"],
        "cities": {
            "Jeddah": {
                "name_ar": "جدة",
                "aliases": ["jiddah", "jedda", "jeda", "جده"],
                "population": 4_700_000,
                "bounds": {"north": 21.72, "south": 21.38, "west": 39.10, "east": 39.28},
                "base_grid_step_km": 1.5,
                "radius": 1500,
            },
            "Makkah": {
                "name_ar": "مكة المكرمة",
                "aliases": ["mecca", "makkah city"],
                "population": 2_000_000,
                "bounds": {"north": 21.46, "south": 21.38, "west": 39.79, "east": 39.90},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Taif": {
                "name_ar": "الطائف",
                "aliases": ["al taif", "altaif", "الطايف"],
                "population": 700_000,
                "bounds": {"north": 21.30, "south": 21.23, "west": 40.48, "east": 40.55},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Rabigh": {
                "name_ar": "رابغ",
                "aliases": [],
                "population": 70_000,
                "bounds": {"north": 22.82, "south": 22.77, "west": 38.96, "east": 39.01},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Al_Qunfudhah": {
                "name_ar": "القنفذة",
                "aliases": ["qunfudhah", "kunfuda"],
                "population": 60_000,
                "bounds": {"north": 19.15, "south": 19.11, "west": 41.07, "east": 41.12},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Madinah_Region": {
        "name_en": "Madinah Region",
        "name_ar": "منطقة المدينة المنورة",
        "aliases": ["madinah", "medina", "المدينة", "المدينة المنورة"],
        "cities": {
            "Madinah": {
                "name_ar": "المدينة المنورة",
                "aliases": ["medina", "madinah city", "al madinah"],
                "population": 1_500_000,
                "bounds": {"north": 24.52, "south": 24.40, "west": 39.55, "east": 39.70},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Yanbu": {
                "name_ar": "ينبع",
                "aliases": ["yanbu al bahr"],
                "population": 300_000,
                "bounds": {"north": 24.12, "south": 24.05, "west": 38.03, "east": 38.10},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
            "AlUla": {
                "name_ar": "العلا",
                "aliases": ["al ula", "alola"],
                "population": 40_000,
                "bounds": {"north": 26.65, "south": 26.60, "west": 37.90, "east": 37.95},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Eastern_Region": {
        "name_en": "Eastern Region",
        "name_ar": "المنطقة الشرقية",
        "aliases": ["eastern", "الشرقية", "sharqiyah"],
        "cities": {
            "Dammam": {
                "name_ar": "الدمام",
                "aliases": ["aldammam"],
                "population": 1_300_000,
                "bounds": {"north": 26.48, "south": 26.38, "west": 50.05, "east": 50.15},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Khobar": {
                "name_ar": "الخبر",
                "aliases": ["al khobar", "alkhobar"],
                "population": 600_000,
                "bounds": {"north": 26.33, "south": 26.26, "west": 50.17, "east": 50.24},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Dhahran": {
                "name_ar": "الظهران",
                "aliases": ["al dhahran"],
                "population": 150_000,
                "bounds": {"north": 26.32, "south": 26.27, "west": 50.10, "east": 50.15},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Jubail": {
                "name_ar": "الجبيل",
                "aliases": ["al jubail"],
                "population": 400_000,
                "bounds": {"north": 27.02, "south": 26.94, "west": 49.62, "east": 49.70},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Hofuf": {
                "name_ar": "الهفوف",
                "aliases": ["al hofuf", "al ahsa", "الأحساء", "الاحساء", "ahsa"],
                "population": 700_000,
                "bounds": {"north": 25.42, "south": 25.32, "west": 49.55, "east": 49.65},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Qatif": {
                "name_ar": "القطيف",
                "aliases": ["al qatif"],
                "population": 200_000,
                "bounds": {"north": 26.57, "south": 26.51, "west": 50.00, "east": 50.05},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
        },
    },
    "Qaseem_Region": {
        "name_en": "Qaseem Region",
        "name_ar": "منطقة القصيم",
        "aliases": ["qaseem", "qassim", "القصيم", "قصيم"],
        "cities": {
            "Buraidah": {
                "name_ar": "بريدة",
                "aliases": ["buraydah", "buraidah city"],
                "population": 750_000,
                "bounds": {"north": 26.40, "south": 26.28, "west": 43.92, "east": 44.05},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Unaizah": {
                "name_ar": "عنيزة",
                "aliases": ["onaizah", "unayzah"],
                "population": 180_000,
                "bounds": {"north": 26.12, "south": 26.06, "west": 43.97, "east": 44.03},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
            "Ar_Rass": {
                "name_ar": "الرس",
                "aliases": ["al rass", "rass"],
                "population": 130_000,
                "bounds": {"north": 25.88, "south": 25.84, "west": 43.48, "east": 43.53},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Al_Mithnab": {
                "name_ar": "المذنب",
                "aliases": ["mithnab"],
                "population": 40_000,
                "bounds": {"north": 25.48, "south": 25.44, "west": 44.24, "east": 44.29},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Al_Bukayriyah": {
                "name_ar": "البكيرية",
                "aliases": ["bukayriyah"],
                "population": 35_000,
                "bounds": {"north": 26.15, "south": 26.11, "west": 43.76, "east": 43.81},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Aseer_Region": {
        "name_en": "Aseer Region",
        "name_ar": "منطقة عسير",
        "aliases": ["aseer", "asir", "عسير"],
        "cities": {
            "Abha": {
                "name_ar": "أبها",
                "aliases": [],
                "population": 500_000,
                "bounds": {"north": 18.25, "south": 18.19, "west": 42.48, "east": 42.54},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Khamis_Mushait": {
                "name_ar": "خميس مشيط",
                "aliases": ["khamis mushait", "khamis"],
                "population": 600_000,
                "bounds": {"north": 18.33, "south": 18.27, "west": 42.70, "east": 42.77},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Bisha": {
                "name_ar": "بيشة",
                "aliases": [],
                "population": 100_000,
                "bounds": {"north": 20.02, "south": 19.97, "west": 42.58, "east": 42.64},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
            "Namas": {
                "name_ar": "النماص",
                "aliases": ["al namas"],
                "population": 35_000,
                "bounds": {"north": 19.15, "south": 19.11, "west": 42.12, "east": 42.17},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Tabuk_Region": {
        "name_en": "Tabuk Region",
        "name_ar": "منطقة تبوك",
        "aliases": ["tabuk", "تبوك", "tabook"],
        "cities": {
            "Tabuk": {
                "name_ar": "تبوك",
                "aliases": ["tabuk city"],
                "population": 600_000,
                "bounds": {"north": 28.42, "south": 28.35, "west": 36.52, "east": 36.62},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Umluj": {
                "name_ar": "أملج",
                "aliases": [],
                "population": 30_000,
                "bounds": {"north": 25.07, "south": 25.03, "west": 37.25, "east": 37.30},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Duba": {
                "name_ar": "ضباء",
                "aliases": ["dhaba"],
                "population": 25_000,
                "bounds": {"north": 27.37, "south": 27.33, "west": 36.51, "east": 36.56},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Hail_Region": {
        "name_en": "Hail Region",
        "name_ar": "منطقة حائل",
        "aliases": ["hail", "ha'il", "حائل", "حايل"],
        "cities": {
            "Hail": {
                "name_ar": "حائل",
                "aliases": ["hail city"],
                "population": 450_000,
                "bounds": {"north": 27.56, "south": 27.48, "west": 41.66, "east": 41.75},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Baqaa": {
                "name_ar": "بقعاء",
                "aliases": [],
                "population": 30_000,
                "bounds": {"north": 27.92, "south": 27.88, "west": 42.38, "east": 42.43},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Northern_Borders_Region": {
        "name_en": "Northern Borders Region",
        "name_ar": "منطقة الحدود الشمالية",
        "aliases": ["northern borders", "الحدود الشمالية", "الشمالية"],
        "cities": {
            "Arar": {
                "name_ar": "عرعر",
                "aliases": [],
                "population": 150_000,
                "bounds": {"north": 31.02, "south": 30.93, "west": 40.14, "east": 40.26},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Rafha": {
                "name_ar": "رفحاء",
                "aliases": [],
                "population": 70_000,
                "bounds": {"north": 29.65, "south": 29.59, "west": 43.46, "east": 43.55},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
            "Turaif": {
                "name_ar": "طريف",
                "aliases": [],
                "population": 40_000,
                "bounds": {"north": 31.70, "south": 31.65, "west": 38.63, "east": 38.70},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
        },
    },
    "Jazan_Region": {
        "name_en": "Jazan Region",
        "name_ar": "منطقة جازان",
        "aliases": ["jazan", "jizan", "جازان", "جيزان"],
        "cities": {
            "Jazan": {
                "name_ar": "جازان",
                "aliases": ["jizan city"],
                "population": 200_000,
                "bounds": {"north": 16.92, "south": 16.86, "west": 42.53, "east": 42.60},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Sabya": {
                "name_ar": "صبيا",
                "aliases": [],
                "population": 80_000,
                "bounds": {"north": 17.17, "south": 17.13, "west": 42.62, "east": 42.67},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Abu_Arish": {
                "name_ar": "أبو عريش",
                "aliases": [],
                "population": 60_000,
                "bounds": {"north": 16.98, "south": 16.94, "west": 42.78, "east": 42.83},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "Najran_Region": {
        "name_en": "Najran Region",
        "name_ar": "منطقة نجران",
        "aliases": ["najran", "نجران"],
        "cities": {
            "Najran": {
                "name_ar": "نجران",
                "aliases": ["najran city"],
                "population": 350_000,
                "bounds": {"north": 17.53, "south": 17.47, "west": 44.20, "east": 44.28},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Sharurah": {
                "name_ar": "شرورة",
                "aliases": [],
                "population": 80_000,
                "bounds": {"north": 17.50, "south": 17.46, "west": 47.10, "east": 47.15},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "AlBaha_Region": {
        "name_en": "Al Baha Region",
        "name_ar": "منطقة الباحة",
        "aliases": ["al baha", "baha", "الباحة"],
        "cities": {
            "Al_Baha": {
                "name_ar": "الباحة",
                "aliases": ["baha city"],
                "population": 100_000,
                "bounds": {"north": 20.02, "south": 19.98, "west": 41.45, "east": 41.50},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
            "Baljurashi": {
                "name_ar": "بلجرشي",
                "aliases": [],
                "population": 60_000,
                "bounds": {"north": 19.87, "south": 19.83, "west": 41.60, "east": 41.65},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
        },
    },
    "AlJawf_Region": {
        "name_en": "Al Jawf Region",
        "name_ar": "منطقة الجوف",
        "aliases": ["al jawf", "jawf", "الجوف"],
        "cities": {
            "Sakakah": {
                "name_ar": "سكاكا",
                "aliases": [],
                "population": 200_000,
                "bounds": {"north": 29.99, "south": 29.93, "west": 40.17, "east": 40.24},
                "base_grid_step_km": 2.0,
                "radius": 2000,
            },
            "Dumat_Al_Jandal": {
                "name_ar": "دومة الجندل",
                "aliases": ["domat al jandal"],
                "population": 50_000,
                "bounds": {"north": 29.83, "south": 29.79, "west": 39.85, "east": 39.90},
                "base_grid_step_km": 3.0,
                "radius": 3000,
            },
            "Qurayyat": {
                "name_ar": "القريات",
                "aliases": ["gurayat", "al qurayyat"],
                "population": 120_000,
                "bounds": {"north": 31.35, "south": 31.30, "west": 37.33, "east": 37.38},
                "base_grid_step_km": 2.5,
                "radius": 2500,
            },
        },
    },
}
